# Makefile for GridrecIDL for Linux

SHELL = /bin/sh
CFLAGS = -O -KPIC -DIDL
INCLUDES=-I../
MAKE = make
OBJ = grid.o GridrecIDL.o grid_math.o pswf.o filters.o fft.o
SRC = grid.c GridrecIDL.c grid_math.c pswf.c filters.c fft.c

GridrecIDL.so: $(OBJ)
	@echo "Creating GridrecIDL.so"
	$(LD) -G -o$@ $(OBJ) -lm;

clean:
	rm *.o GridrecIDL.so 

